name: CD

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - run: npm run build
      - run: npm run bundle # Webpack


#     - run: npm run deploy:test
#       if: github.ref == 'refs/heads/develop'

      - run: ENV=test npm run test:e2e
        if: github.ref == 'refs/heads/develop'


#     - run: npm run deploy:prod
#       if: github.ref == 'refs/heads/master'

      - run: ENV=prod npm run test:e2e
        if: github.ref == 'refs/heads/master'

#     ToDo: Canary-Releases?
