name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - run: npm run test:ut
      - run: npm run test:it

      - run: npm run build
      - run: npm run bundle # Webpack

#     - run: npm run deploy:test
      - run: ENV=test npm run test:ee

#     - run: npm run deploy:prod
      - run: ENV=prod npm run test:ee

#     ToDo: Canary-Releases?
