name: Node.js CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:12-alpine
    services:
      dynamodb-local:
        image: amazon/dynamodb-local
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: npm run test:unit

      - run: npm run test:int
        env:
          DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      - run: npm run test:e2e
        env:
          DYNAMODB_ENDPOINT: http://dynamodb-local:8000
