name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: pip install aws-sam-cli
      - run: sam --version

      - run: npm install

      - run: npm run build
      - run: npm run test:unit

#     - run: sam local ...
      - run: npm run test:intr

#     Todo: ...
